
###
GET http://localhost:3000/docentes

###

GET http://localhost:3000/alumnos

###

GET http://localhost:3000/alumnos/6aa1a451de0fb127693ef4a9

###

GET http://localhost:3000/alumnos/3




###

GET http://localhost:3000/alumnos/141

###


# POST http://localhost:3000/alumnos
# Content-Type: application/json

# {
#         "id": 300,
#         "nombre": "Lucia Fernandez",
#         "carrera": "metalurgica",
#         "correo": "lucifernandez@gmail.com"
# }



POST http://localhost:3000/alumnos
Content-Type: application/json


{
        "legajo": 301,
        "nombre": "Lucia Fernandez",
        "carrera": "metalurgica",
        "correo": "lucifernandez@gmail.com"
}


###

POST http://localhost:3000/alumnos
Content-Type: application/json

{
        "legajo": 304,
        "nombre": "Martin Gallanes",
        "carrera": "Metafisica",
        "correo": "martingallanes@gmail.com"
}

###
PUT http://localhost:3000/alumnos/303
Content-Type: application/json

{
        "legajo": 303,
        "nombre": "Martin Gallardo",
        "carrera": "Metafisica neutoneana",
        "correo": "martingallanes@gmail.com"
}


###
GET http://localhost:3000/alumnos



###
DELETE http://localhost:3000/alumnos/303


###

USE http://localhost:3000/alumnos

###
POST http://localhost:3000/alumnos/303
Content-Type: application/json

{
        "id": 12,
        "nombre": "Mateo",
        "carrera": "Metafisica",
        "correo": "martingallanes@gmail.com"
}